name = "ZayForge"
default_targets = ["win32", "win64", "appimage", "lovejs", "macos"]
build_directory = "makelove-build"
icon_file = "assets/images/icon.png"
love_version = "11.5"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-./*.toml",
    "-./*.md",
    "-./LICENSE",
    "-./makelove-build/*",
    "-./release/*",
    "-./.vscode/*",
    "-./*.sh"
]


[windows.exe_metadata]
CompanyName = "ZayFire Studios"
FileDescription = "ZayForge is a 2D top-down survival/RPG game inspired by Minecraft, built with LÖVE (Love2D). Explore, survive, and craft in a pixel-art world with top-down action and RPG elements."

[macos.app_metadata]
CFBundleName = "ZayForge"
CFBundleDisplayName = "ZayForge"
CFBundleIdentifier = "com.zayfirestudios.zayforge"

[linux.desktop_file_metadata]
Comment = "ZayForge is a 2D top-down survival/RPG game inspired by Minecraft, built with LÖVE (Love2D). Explore, survive, and craft in a pixel-art world with top-down action and RPG elements."
Categories = "Game;"